# https://taskfile.dev
version: '2'
tasks:
  t:
    desc: test
    cmds:
      - go test -v ./...
    silent: true
  stest:
    desc: system test
    cmds:
      - echo BASE_URL=$BASE_URL
      - go test ./http_system_test.go
    env:
      BASE_URL: https://asia-northeast1-shareup.cloudfunctions.net/Hello

  deploy:
    desc: create and redeploy cloud function
    cmds:
      - gcloud functions deploy Hello --entry-point Hello --runtime go113 --trigger-http \
        --allow-unauthenticated --memory=128MB --region=asia-northeast1
  trigger:
    desc: trigger cloud function, Great!
    cmds:
      - gcloud functions call Hello --region=asia-northeast1
  list:
    desc: list functions
    cmds:
      - gcloud functions list
  del:
    desc: remove function
    cmds:
      #- gcloud functions delete Hello --region=us-central1
      - gcloud functions delete Hello --region=asia-northeast1 --quiet
